DesignPatternsAsp/Models/ErrorViewModel.cs
using System;

namespace DesignPatternsAsp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DesignPatternsAsp/Models/ViewModels/BeerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesignPatternsAsp.Models.ViewModels
{
    public class BeerViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Style { get; set; }
    }
}

DesignPatternsAsp/Models/ViewModels/FormBeerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesignPatternsAsp.Models.ViewModels
{
    public class FormBeerViewModel
    {
        [Required]
        [Display(Name = "Nombre")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Estilo")]
        public string Style { get; set; }

        [Display(Name = "Marca")]
        public Guid? BrandId { get; set; }

        [Display(Name = "Otra marca")]
        public string OtherBrand { get; set; }
    }
}

DesignPatternsAsp/Controllers/BeerController.cs
using DesignPatterns.Models.Data;
using DesignPatterns.Repository;
using DesignPatternsAsp.Models.ViewModels;
using DesignPatternsAsp.Strategies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesignPatternsAsp.Controllers
{
    public class BeerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BeerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<BeerViewModel> beers = from d in _unitOfWork.Beers.Get()
                                               select new BeerViewModel
                                               {
                                                   Id = d.BeerId,
                                                   Name = d.Name,
                                                   Style = d.Style
                                               };
            return View("Index", beers);
        }

        [HttpGet]
        public IActionResult Add()
        {
            GetBrandsData();
            return View();
        }

        [HttpPost]
        public IActionResult Add(FormBeerViewModel beerVM)
        {
            if (!ModelState.IsValid)
            {
                GetBrandsData();
                return View("Add", beerVM);
            }

            var context = beerVM.BrandId == null ?
                             new BeerContext(new BeerWithbrandStrategy()) :
                             new BeerContext(new BeerStrategy());

            context.Add(beerVM, _unitOfWork);

            return RedirectToAction("Index");

        }

        #region HELPERS
        private void GetBrandsData()
        {
            var brands = _unitOfWork.Brands.Get();
            ViewBag.Brands = new SelectList(brands, "BrandId", "Name");
        }
        #endregion
    }
}

DesignPatternsAsp/Controllers/GeneratorFileController.cs
using DesignPatterns.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tools.Generator;

namespace DesignPatternsAsp.Controllers
{
    public class GeneratorFileController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private GeneratorConcreteBuilder _generatorConcreteBuilder;

        public GeneratorFileController(IUnitOfWork unitOfWork, GeneratorConcreteBuilder generatorConcreteBuilder)
        {
            _unitOfWork = unitOfWork;
            _generatorConcreteBuilder = generatorConcreteBuilder;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateFile(int optionFile)
        {
            try
            {
                var beers = _unitOfWork.Beers.Get();
                List<string> content = beers.Select(d => d.Name).ToList();
                string path = "file" + DateTime.Now.Ticks + new Random().Next(1000) + ".txt";
                var generatorDirector = new GeneratorDirector(_generatorConcreteBuilder);

                if(optionFile == 1)
                {
                    generatorDirector.CreateSimpleJsonGenerator(content, path);
                }
                else
                {
                    generatorDirector.CreateSimplePipeGenerator(content, path);
                }

                var generator = _generatorConcreteBuilder.GetGenerator();
                generator.Save();

                return Json("Archivo generado");

            }catch(Exception ex)
            {
                return BadRequest();
            }
        }
    }
}

DesignPatternsAsp/Controllers/HomeController.cs
using DesignPatterns.Models.Data;
using DesignPatterns.Repository;
using DesignPatternsAsp.Configuration;
using DesignPatternsAsp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Tools;

namespace DesignPatternsAsp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IOptions<MyConfig> _config;

        private readonly IRepository<Beer> _repository;
        public HomeController(IOptions<MyConfig> config, IRepository<Beer> repository)
        {
            _config = config;
            _repository = repository;
        }

        public IActionResult Index()
        {
            //Factory
            //Log.GetInstance(_config.Value.PathLog).Save("Entro al index");

            IEnumerable<Beer> lst = _repository.Get();

            return View("index", lst);
        }

        //Factory
        /*public IActionResult Privacy()
        {
            Log.GetInstance(_config.Value.PathLog).Save("Entro al privacy");
            return View();
        }*/

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesignPatternsAsp/Controllers/ProductDetailController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tools.Earn;

namespace DesignPatternsAsp.Controllers
{
    public class ProductDetailController : Controller
    {
        private EarnFactory _localEarnFactory;
        private EarnFactory _foreignEarnFactory;

        public ProductDetailController(LocalEarnFactory localEarnFactory, ForeignEarnFactory foreignEarnFactory)
        {
            _localEarnFactory = localEarnFactory;
            _foreignEarnFactory = foreignEarnFactory;
        }

        public IActionResult Index(decimal total)
        {
            //factories
            /*LocalEarnFactory localEarnFactory = new LocalEarnFactory(0.20m);*/
            /*ForeignEarnFactory foreignEarnFactory = new ForeignEarnFactory(0.30m, 20);*/

            //products
            var localEarn = _localEarnFactory.GetEarn();
            var foreignEarn = _foreignEarnFactory.GetEarn();

            //total
            ViewBag.totalLocal = total + localEarn.Earn(total);
            ViewBag.totalForeign = total + foreignEarn.Earn(total);

            return View();
        }
    }
}

DesignPatternsAsp/Views/Beer/Add.cshtml
@model DesignPatternsAsp.Models.ViewModels.FormBeerViewModel

<form asp-controller="Beer" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Style"></label>
        <input class="form-control" asp-for="Style" />
        <span asp-validation-for="Style" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BrandId"></label>
        <select class="form-control" asp-for="BrandId" asp-items="@ViewBag.Brands">
            <option value="">---Selecciona Marca---</option>
        </select>
        <span asp-validation-for="BrandId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="OtherBrand"></label>
        <input class="form-control" asp-for="OtherBrand" />
        <span asp-validation-for="OtherBrand" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button class="btn btn-primary">
            Guardar
        </button>
    </div>
</form>

DesignPatternsAsp/Views/Beer/Index.cshtml
@using DesignPatternsAsp.Models.ViewModels
@model IEnumerable<BeerViewModel>

<div class="row">
    <div class="col-12">
        <a class="btn btn-primary" href="~/Beer/Add">
            Nueva Cerveza
        </a>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class=" table">
            <tr>
                <th>Nombre</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name.</td>
                </tr>
            }
        </table>
    </div>
</div>

DesignPatternsAsp/Views/GeneratorFile/Index.cshtml
<div class="row">
    <div class="col-8 offset-2">
        <div class="form-group">
            <select id="optionFile" class="form-control">
                <option value="1">Json</option>
                <option value="2">Pipe</option>
            </select>
        </div>
        <div class="form-group">
            <button class="btn btn-success" onclick="generate()">
                Generar
            </button>
        </div>
    </div>
</div>

<script>
    function generate() {
        let optionFile = document.getElementById("optionFile").value;
        fetch("@Url.Content("~/GeneratorFile/CreateFile")" + "?optionFile=" + optionFile)
            .then(res => res.json())
            .then(json => alert(json));
    }
</script>

DesignPatternsAsp/Views/Home/Index.cshtml
@using DesignPatterns.Models.Data
@model IEnumerable<Beer>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-12">
        @foreach (var item in Model)
        {
            <p>@item.Name</p>
        }
    </div>
</div>

DesignPatternsAsp/Views/ProductDetail/Index.cshtml
@{ 
    decimal totalLocal = (decimal)ViewBag.totalLocal;
    decimal totalForeign = (decimal)ViewBag.totalForeign;
}

<div class="row">
    <div class="col-12">
        <label>Total local</label>
        <b>@totalLocal</b>
        <br />
        <label>Total extranjero</label>
        <b>@totalForeign</b>
        <br />
    </div>
</div>

DesignPatternsAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesignPatternsAsp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesignPatternsAsp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DesignPatternsAsp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>